
on:
  push:
    tags: ["v*"]
    branches: [master]

jobs:
  make-release:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: $${{ env.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current tag
        id: current-tag
        run: |
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Debug
        run: echo ${{ steps.current-tag.outputs.tag }}
      