
name: Make release

on:
  push:
    tags: ["v*"]

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current tag
        id: current-tag
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          echo "VERSION=$(git describe --tags --abbrev=0 | cut -c 2-)" >> $GITHUB_OUTPUT

      - name: Create body
        id: create-body
        run: >
          echo "BODY='## Version Dependencies\n
          * Plugin: \n
          * App: ${{ steps.current-tag.outputs.VERSION }}\n
          * Model: \n* SNPE: \n* SafieEdgeAppFramework: \n
          * Mininum FW version: \n
          ## Release Date\n
          * Staging\n
          * Production'" >> $GITHUB_OUTPUT

      - name: Make release
        id: release-note
        run: >
          curl 
          -X POST 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" 
          https://api.github.com/repos/${{ github.repository }}/releases 
          -d '{"tag_name":"${{ steps.current-tag.outputs.TAG }}",
          "name":"${{ steps.current-tag.outputs.TAG }}",
          "body":"${{ steps.create-body.outputs.BODY }}",
          "draft":false,
          "prerelease":true,
          "generate_release_notes":true}'
