
name: Make release

on:
  push:
    tags: ["v*"]

jobs:
  make-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current tag
        id: current-tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Debug
        run: echo ${{ steps.current-tag.outputs.TAG }}

      - name: Make release
        id: release-note
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/releases \
          -d '{"tag_name":"${{ steps.current-tag.outputs.TAG }}","name":"${{ steps.current-tag.outputs.TAG }}","body":"## Version Dependencies","draft":false,"prerelease":true,"generate_release_notes":true}'
